name: Create a comment on new issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment_with_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: |
          echo '${{ toJSON(github.event) }}' | jq
        shell: bash

      - name: Create a comment with action
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line comment created **by the create-or-update-comment action** for issue:

            > ${{ github.event.issue.title }}

            - Opened by **@${{ github.event.issue.user.login }}**
            - Using GitHub **Markdown** and reactions :sparkles:
            - Powered by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: "+1"

  comment_with_api:
    runs-on: ubuntu-latest
    steps:
      - name: Create a multi-line comment with GitHub CLI API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPOSITORY: ${{ github.repository }}
        run: |
          ORG_REPO=(${REPOSITORY//\// })
          ORG=${ORG_REPO[0]}
          REPO=${ORG_REPO[1]}

          COMMENT_BODY=$(cat <<EOF
          This is a different multi-line comment posted **using the GitHub CLI API** for issue:

          > ${{ github.event.issue.title }}

          - Created by **@${{ github.event.issue.user.login }}**
          - Sent via \`gh api\` command in a workflow
          - See more about the CLI here: [GitHub CLI][1]

          [1]: https://github.com/cli/cli
          EOF
                    )

          gh api -X POST \
            /repos/$ORG/$REPO/issues/$ISSUE_NUMBER/comments \
            -f body="$COMMENT_BODY"
